checkpoint_path: "runs/dasr_testing"  # Path to save model checkpoints

train_imgs: "Data/images/train/"
train_txt: "Data/train.txt"

epochs: 100                 # Number of epochs to train
run_name: "dasr_testing"        # Name of the run for wandb loggin

queue_size: 40
temperature: 0.999
momentum: 0.07
lr: 0.1
weight_decay: 0.001
batch_size: 20
patch_size: 256 
dim: 256
step_size: 10
num_workers: 16
